### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by ejmurray** [mcs07/conda-cde#1]
The installation works on my mac using conda. However, trying to use the command "conda install -c chemdataextractor chemdataextractor" gives the following error message in the console

"Could not find URL: https://github.com/mcs07/ChemDataExtractor/win-64/"

The same error comes up when using the instructions from the Anaconda repo
"conda install --channel ChemDataExtractor package"

**Comment by mcs07** [comment]
Sounds like you may have added `https://github.com/mcs07/ChemDataExtractor` as a channel in your conda config. You don't need to do this. Check by running:

```
conda config --get channels
```

If the above address is shown, remove it using:

```
conda config --remove channels https://github.com/mcs07/ChemDataExtractor
```

**Comment by ejmurray** [comment]
I did add the channel manually to the .condarc file over a week ago and have now removed it as you explained above. The problem now is that it can't find: "https://github.com/conda-forge/win-64/"

I've switched to using a linux box that I can ssh to which has anaconda running on it and have successfully installed it in an environment in there. The examples are working in a Jupyter notebook.

**Comment by mcs07** [comment]
It's possible you also have "https://github.com/conda-forge" in your channels. The correct way to add that would be `conda config --add channels conda-forge`
